const fs = require('fs');
const path = require('path');

const dir = './streaming_links';
const outputFile = './duplicate_posts.md';

function run() {
    if (!fs.existsSync(dir)) {
        console.error(`Directory ${dir} not found!`);
        return;
    }

    const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));
    console.log(`Scanning ${files.length} files for duplicates...`);

    const mediaMap = {};

    // Group files by type and ID
    files.forEach(file => {
        // Matches: admin_movie_123.json OR normal_tv_456.json
        const match = file.match(/^(admin|normal)_(movie|tv)_(\d+)\.json$/);
        if (match) {
            const mode = match[1];
            const type = match[2];
            const id = match[3];
            const key = `${type}_${id}`;

            if (!mediaMap[key]) {
                mediaMap[key] = { modes: [], files: [], id, type };
            }
            mediaMap[key].modes.push(mode);
            mediaMap[key].files.push(file);
        }
    });

    const duplicates = [];

    // Check for keys that have both admin and normal
    Object.keys(mediaMap).forEach(key => {
        const entry = mediaMap[key];
        if (entry.modes.includes('admin') && entry.modes.includes('normal')) {
            // It's a duplicate. Let's read one of the files to get the title.
            const filePath = path.join(dir, entry.files[0]);
            try {
                const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
                duplicates.push({
                    title: content.title || content.name || 'Unknown Title',
                    type: entry.type,
                    id: entry.id,
                    files: entry.files
                });
            } catch (err) {
                console.error(`Error reading ${filePath}:`, err);
            }
        }
    });

    // Generate Markdown output
    const now = new Date().toUTCString();
    let mdContent = `# DanieWatch Duplicate Posts Report\n`;
    mdContent += `*Last Updated: ${now}*\n\n`;
    mdContent += `This file is auto-generated by the bot. It lists all media that have **both** Admin and Normal JSON files uploaded in the database.\n\n`;

    if (duplicates.length === 0) {
        mdContent += `✅ **No duplicate posts found!** Database is clean.\n`;
    } else {
        mdContent += `⚠️ **Found ${duplicates.length} duplicate post(s):**\n\n`;
        duplicates.forEach((dup, index) => {
            mdContent += `### ${index + 1}. ${dup.title}\n`;
            mdContent += `- **Type**: ${dup.type.toUpperCase()}\n`;
            mdContent += `- **TMDB ID**: \`${dup.id}\`\n`;
            mdContent += `- **Conflicting Files**:\n`;
            dup.files.forEach(f => {
                mdContent += `  - \`${f}\`\n`;
            });
            mdContent += `\n`;
        });
    }

    fs.writeFileSync(outputFile, mdContent, 'utf8');
    console.log(`✅ Duplicate check complete! Found ${duplicates.length} duplicates. Report saved to ${outputFile}`);
}

run();
