const fs = require('fs');
const path = require('path');

const indexFile = './index.json';
const oldIndexFile = './old_index_snapshot.json';
const recordFile = './posting_record.json';

function run() {
    // ─── Step 1: Load the NEW index (just generated by generate_index.js) ───
    if (!fs.existsSync(indexFile)) {
        console.error('❌ index.json not found! Run generate_index.js first.');
        return;
    }

    let newIndex;
    try {
        newIndex = JSON.parse(fs.readFileSync(indexFile, 'utf8'));
    } catch (err) {
        console.error('❌ Failed to parse index.json:', err.message);
        return;
    }

    const newPosts = newIndex.posts || [];
    const newPostMap = new Map();
    newPosts.forEach(p => {
        const key = `${p.type}_${p.id}`;
        newPostMap.set(key, p);
    });

    // ─── Step 2: Load the OLD index snapshot (saved before generate_index.js ran) ───
    let oldPostKeys = new Set();

    if (fs.existsSync(oldIndexFile)) {
        try {
            const oldIndex = JSON.parse(fs.readFileSync(oldIndexFile, 'utf8'));
            if (oldIndex.posts) {
                oldIndex.posts.forEach(p => {
                    oldPostKeys.add(`${p.type}_${p.id}`);
                });
            }
        } catch (err) {
            console.log('⚠️ Could not parse old index snapshot, treating as empty.');
        }
    } else {
        console.log('ℹ️ No old index snapshot found. Starting fresh — only future additions will be tracked.');
        // On first run with no snapshot, we treat ALL current posts as "existing"
        // so no batch is created. Future runs will detect new additions.
        
        // Create the initial posting_record.json with empty batches
        if (!fs.existsSync(recordFile)) {
            const initialRecord = {
                last_updated: new Date().toISOString(),
                total_posts: newPosts.length,
                total_batches: 0,
                batches: []
            };
            fs.writeFileSync(recordFile, JSON.stringify(initialRecord, null, 2));
            console.log(`✅ posting_record.json initialized (0 batches, ${newPosts.length} existing posts tracked).`);
        }
        return;
    }

    // ─── Step 3: Compute the DIFF — find ADDED and REMOVED posts ───
    const addedPosts = [];
    const removedKeys = new Set();

    // Find posts added (in new but NOT in old)
    newPostMap.forEach((post, key) => {
        if (!oldPostKeys.has(key)) {
            addedPosts.push({
                title: post.title || 'Unknown Title',
                tmdb_id: post.id || '',
                imdb_id: post.imdb_id || '',
                type: post.type || 'movie',
                year: post.year || ''
            });
        }
    });

    // Find posts removed (in old but NOT in new)
    const newPostKeys = new Set();
    newPosts.forEach(p => newPostKeys.add(`${p.type}_${p.id}`));
    oldPostKeys.forEach(key => {
        if (!newPostKeys.has(key)) {
            removedKeys.add(key);
        }
    });

    if (addedPosts.length === 0 && removedKeys.size === 0) {
        // Even if no new/removed posts, still backfill year for existing entries
        if (fs.existsSync(recordFile)) {
            try {
                const existingRecord = JSON.parse(fs.readFileSync(recordFile, 'utf8'));
                let backfilled = 0;
                existingRecord.batches.forEach(batch => {
                    batch.posts.forEach(p => {
                        if (!p.year || p.year === '') {
                            const key = `${p.type}_${p.tmdb_id}`;
                            const indexPost = newPostMap.get(key);
                            if (indexPost && indexPost.year) {
                                p.year = indexPost.year;
                                backfilled++;
                            }
                        }
                    });
                });
                if (backfilled > 0) {
                    existingRecord.last_updated = new Date().toISOString();
                    fs.writeFileSync(recordFile, JSON.stringify(existingRecord, null, 2));
                    console.log(`📅 Backfilled year for ${backfilled} existing post(s). No other changes.`);
                } else {
                    console.log('ℹ️ No new or removed posts detected. Posting record unchanged.');
                }
            } catch (err) {
                console.log('ℹ️ No new or removed posts detected. Posting record unchanged.');
            }
        } else {
            console.log('ℹ️ No new or removed posts detected. Posting record unchanged.');
        }
        return;
    }

    // ─── Step 4: Sort new posts alphabetically (A → Z) by title ───
    addedPosts.sort((a, b) => {
        const titleA = a.title.toLowerCase();
        const titleB = b.title.toLowerCase();
        if (titleA < titleB) return -1;
        if (titleA > titleB) return 1;
        return 0;
    });

    // ─── Step 5: Load existing posting_record.json (or create new) ───
    let record;

    if (fs.existsSync(recordFile)) {
        try {
            record = JSON.parse(fs.readFileSync(recordFile, 'utf8'));
        } catch (err) {
            console.log('⚠️ Could not parse existing posting_record.json, creating fresh.');
            record = null;
        }
    }

    if (!record) {
        record = {
            last_updated: '',
            total_posts: 0,
            total_batches: 0,
            batches: []
        };
    }

    // ─── Step 5a: Backfill 'year' for existing posts missing it ───
    let backfilledCount = 0;
    record.batches.forEach(batch => {
        batch.posts.forEach(p => {
            if (!p.year || p.year === '') {
                const key = `${p.type}_${p.tmdb_id}`;
                const indexPost = newPostMap.get(key);
                if (indexPost && indexPost.year) {
                    p.year = indexPost.year;
                    backfilledCount++;
                }
            }
        });
    });
    if (backfilledCount > 0) {
        console.log(`📅 Backfilled year for ${backfilledCount} existing post(s).`);
    }

    // ─── Step 5b: Purge REMOVED posts from all batches ───
    if (removedKeys.size > 0) {
        let totalRemoved = 0;
        record.batches.forEach(batch => {
            const before = batch.posts.length;
            batch.posts = batch.posts.filter(p => {
                const key = `${p.type}_${p.tmdb_id}`;
                return !removedKeys.has(key);
            });
            const removed = before - batch.posts.length;
            totalRemoved += removed;
            batch.total_in_batch = batch.posts.length;
        });

        // Remove batches that became empty after purging
        record.batches = record.batches.filter(b => b.posts.length > 0);

        if (totalRemoved > 0) {
            console.log(`🗑️ Purged ${totalRemoved} removed post(s) from posting record.`);
        }

        // If no new posts to add, just save and exit
        if (addedPosts.length === 0) {
            record.total_batches = record.batches.length;
            record.total_posts = newPosts.length;
            record.last_updated = new Date().toISOString();
            fs.writeFileSync(recordFile, JSON.stringify(record, null, 2));
            console.log(`   📊 Total batches: ${record.total_batches}`);
            console.log(`   📁 Total posts in database: ${record.total_posts}`);
            return;
        }
    }

    // ─── Step 6: Create or merge into today's batch (1 batch per day) ───
    const now = new Date();
    const todayDate = now.toISOString().split('T')[0]; // "YYYY-MM-DD"
    const todayReadable = now.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });

    // Check if a batch for today already exists
    let existingBatchIndex = record.batches.findIndex(b => b.date_key === todayDate);

    if (existingBatchIndex !== -1) {
        // Merge new posts into today's existing batch
        // IMPORTANT: Preserve existing post order (user may have manually rearranged)
        const existingBatch = record.batches[existingBatchIndex];

        // Build a set of already-tracked post keys to avoid duplicates
        const existingKeys = new Set(
            existingBatch.posts.map(p => `${p.type}_${p.tmdb_id}`)
        );

        // Filter to only truly new posts (not already in batch)
        const trulyNew = addedPosts.filter(p => {
            const key = `${p.type}_${p.tmdb_id}`;
            return !existingKeys.has(key);
        });

        // PREPEND new posts ABOVE existing ones (don't rearrange existing order)
        existingBatch.posts = [...trulyNew, ...existingBatch.posts];
        existingBatch.total_in_batch = existingBatch.posts.length;
        existingBatch.last_modified = now.toISOString();

        // Move today's batch to the TOP if it isn't already there
        if (existingBatchIndex !== 0) {
            record.batches.splice(existingBatchIndex, 1);
            record.batches.unshift(existingBatch);
        }

        console.log(`✅ Posting record updated! (merged into today's batch)`);
        console.log(`   📦 Batch "${todayReadable}": now ${existingBatch.total_in_batch} post(s) total`);
    } else {
        // Create a new batch for today — INSERT AT THE TOP so latest is always first
        const newBatch = {
            batch_id: record.batches.length + 1,
            date_key: todayDate,
            date: todayReadable,
            timestamp: now.toISOString(),
            total_in_batch: addedPosts.length,
            posts: addedPosts
        };

        record.batches.unshift(newBatch);
        console.log(`✅ Posting record updated! (new batch created — added to top)`);
        console.log(`   📦 Batch "${todayReadable}": ${addedPosts.length} new post(s)`);
    }

    // ─── Step 7: Save ───
    record.total_batches = record.batches.length;
    record.total_posts = newPosts.length;
    record.last_updated = now.toISOString();

    fs.writeFileSync(recordFile, JSON.stringify(record, null, 2));

    console.log(`   📊 Total batches: ${record.total_batches}`);
    console.log(`   📁 Total posts in database: ${record.total_posts}`);

    // Print the new posts
    console.log(`\n   New posts added (A→Z):`);
    addedPosts.forEach((p, i) => {
        console.log(`   ${i + 1}. ${p.title} [${p.type.toUpperCase()}] (TMDB: ${p.tmdb_id}, IMDB: ${p.imdb_id || 'N/A'}, Year: ${p.year || 'N/A'})`);
    });
}

run();
