const fs = require('fs');
const path = require('path');

const indexFile = './index.json';
const oldIndexFile = './old_index_snapshot.json';
const recordFile = './posting_record.json';

function run() {
    // ─── Step 1: Load the NEW index (just generated by generate_index.js) ───
    if (!fs.existsSync(indexFile)) {
        console.error('❌ index.json not found! Run generate_index.js first.');
        return;
    }

    let newIndex;
    try {
        newIndex = JSON.parse(fs.readFileSync(indexFile, 'utf8'));
    } catch (err) {
        console.error('❌ Failed to parse index.json:', err.message);
        return;
    }

    const newPosts = newIndex.posts || [];
    const newPostMap = new Map();
    newPosts.forEach(p => {
        const key = `${p.type}_${p.id}`;
        newPostMap.set(key, p);
    });

    // ─── Step 2: Load the OLD index snapshot (saved before generate_index.js ran) ───
    let oldPostKeys = new Set();

    if (fs.existsSync(oldIndexFile)) {
        try {
            const oldIndex = JSON.parse(fs.readFileSync(oldIndexFile, 'utf8'));
            if (oldIndex.posts) {
                oldIndex.posts.forEach(p => {
                    oldPostKeys.add(`${p.type}_${p.id}`);
                });
            }
        } catch (err) {
            console.log('⚠️ Could not parse old index snapshot, treating as empty.');
        }
    } else {
        console.log('ℹ️ No old index snapshot found. Starting fresh — only future additions will be tracked.');
        // On first run with no snapshot, we treat ALL current posts as "existing"
        // so no batch is created. Future runs will detect new additions.
        
        // Create the initial posting_record.json with empty batches
        if (!fs.existsSync(recordFile)) {
            const initialRecord = {
                last_updated: new Date().toISOString(),
                total_posts: newPosts.length,
                total_batches: 0,
                batches: []
            };
            fs.writeFileSync(recordFile, JSON.stringify(initialRecord, null, 2));
            console.log(`✅ posting_record.json initialized (0 batches, ${newPosts.length} existing posts tracked).`);
        }
        return;
    }

    // ─── Step 3: Compute the DIFF — find posts in new but NOT in old ───
    const addedPosts = [];

    newPostMap.forEach((post, key) => {
        if (!oldPostKeys.has(key)) {
            addedPosts.push({
                title: post.title || 'Unknown Title',
                tmdb_id: post.id || '',
                imdb_id: post.imdb_id || '',
                type: post.type || 'movie'
            });
        }
    });

    if (addedPosts.length === 0) {
        console.log('ℹ️ No new posts detected. Posting record unchanged.');
        // Still update total_posts count in case of removals
        if (fs.existsSync(recordFile)) {
            try {
                const record = JSON.parse(fs.readFileSync(recordFile, 'utf8'));
                record.total_posts = newPosts.length;
                record.last_updated = new Date().toISOString();
                fs.writeFileSync(recordFile, JSON.stringify(record, null, 2));
            } catch (err) {
                // Ignore
            }
        }
        return;
    }

    // ─── Step 4: Sort new posts alphabetically (A → Z) by title ───
    addedPosts.sort((a, b) => {
        const titleA = a.title.toLowerCase();
        const titleB = b.title.toLowerCase();
        if (titleA < titleB) return -1;
        if (titleA > titleB) return 1;
        return 0;
    });

    // ─── Step 5: Load existing posting_record.json (or create new) ───
    let record;

    if (fs.existsSync(recordFile)) {
        try {
            record = JSON.parse(fs.readFileSync(recordFile, 'utf8'));
        } catch (err) {
            console.log('⚠️ Could not parse existing posting_record.json, creating fresh.');
            record = null;
        }
    }

    if (!record) {
        record = {
            last_updated: '',
            total_posts: 0,
            total_batches: 0,
            batches: []
        };
    }

    // ─── Step 6: Create the new batch ───
    const now = new Date();
    const newBatchId = record.total_batches + 1;

    const newBatch = {
        batch_id: newBatchId,
        timestamp: now.toISOString(),
        date: now.toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        }),
        total_in_batch: addedPosts.length,
        posts: addedPosts
    };

    // ─── Step 7: Append batch and save ───
    record.batches.push(newBatch);
    record.total_batches = record.batches.length;
    record.total_posts = newPosts.length;
    record.last_updated = now.toISOString();

    fs.writeFileSync(recordFile, JSON.stringify(record, null, 2));

    console.log(`✅ Posting record updated!`);
    console.log(`   📦 Batch #${newBatchId}: ${addedPosts.length} new post(s) added`);
    console.log(`   📊 Total batches: ${record.total_batches}`);
    console.log(`   📁 Total posts in database: ${record.total_posts}`);

    // Print the new posts
    console.log(`\n   New posts in this batch (A→Z):`);
    addedPosts.forEach((p, i) => {
        console.log(`   ${i + 1}. ${p.title} [${p.type.toUpperCase()}] (TMDB: ${p.tmdb_id}, IMDB: ${p.imdb_id || 'N/A'})`);
    });
}

run();
